packages:
  - packages/*
  - playground
  - docs
  - benchmark
  - ecosystem-ci

patchedDependencies:
  '@vue-macros/volar': patches/@vue-macros__volar.patch

catalog:
  '@nuxt/kit': ^4.5.2
  '@nuxt/schema': ^4.5.2

  '@types/hash-sum': ^1.0.2

  '@vue-macros/volar': ^3.1.4

  hash-sum: ^2.0.0
  unplugin: ^3.0.0
  unplugin-utils: ^0.3.1
  vue: 3.6.0-rc.8
  vite-plus: 0.3.1
  vite: npm:@voidzero-dev/vite-plus-core@0.3.1
  vitest: 4.1.11

allowBuilds:
  esbuild: true
  vue-demi: true

packageExtensions:
  ts-macro@0.3.7:
    peerDependencies:
      typescript: '*'
  '@ts-macro/tsc@0.3.7':
    peerDependencies:
      typescript: '*'
overrides:
  vite@*: 'catalog:'
  vitest@*: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
