packages:
  - packages/*
  - playground
  - docs
  - benchmark

defines:
  - &vue-macros ^3.1.2
  - &ts-macro ^0.3.7
  - &vue 3.6.0-beta.5

catalog:
  '@nuxt/kit': ^3.21.0
  '@nuxt/schema': ^3.21.0

  '@vue/shared': *vue

  '@vue-macros/common': *vue-macros
  '@vue-macros/define-render': *vue-macros
  '@vue-macros/jsx-directive': *vue-macros
  '@vue-macros/volar': *vue-macros

  '@ts-macro/tsc': *ts-macro
  '@types/hash-sum': ^1.0.2
  hash-sum: ^2.0.0
  ts-macro: *ts-macro
  unplugin: ^3.0.0
  unplugin-utils: ^0.3.1
  vite: ^8.0.0-beta.9
  vitest: ^4.0.18
  vue: *vue
