packages:
  - packages/*
  - playground
  - docs
  - benchmark

defines:
  - &vue-macros ^3.1.2
  - &ts-macro ^0.3.6
  - &vue 3.6.0-alpha.7

catalog:
  '@nuxt/kit': ^3.20.2
  '@nuxt/schema': ^3.20.2

  '@vue/shared': *vue

  '@vue-macros/common': *vue-macros
  '@vue-macros/define-render': *vue-macros
  '@vue-macros/jsx-directive': *vue-macros
  '@vue-macros/test-utils': *vue-macros
  '@vue-macros/volar': *vue-macros

  '@ts-macro/tsc': *ts-macro
  '@types/hash-sum': ^1.0.2
  hash-sum: ^2.0.0
  ts-macro: *ts-macro
  unplugin: ^2.3.11
  unplugin-utils: ^0.2.5
  vite: ^8.0.0-beta.5
  vitest: ^3.2.4
  vue: *vue
