import { defineConfig } from 'vite-plus'

export default defineConfig({
  staged: {
    '*': 'vp check --fix',
  },
  fmt: {
    semi: false,
    singleQuote: true,
  },
  lint: {
    plugins: ['oxc', 'typescript', 'unicorn', 'react', 'import', 'node', 'jsdoc'],
    jsPlugins: [
      {
        name: 'vite-plus',
        specifier: 'vite-plus/oxlint-plugin',
      },
    ],
    categories: {
      correctness: 'warn',
    },
    options: {
      typeAware: true,
      typeCheck: true,
    },
    env: {
      builtin: true,
      browser: true,
      es2026: true,
      node: true,
    },
    ignorePatterns: [
      '**/wasi-worker**',
      '**/compiler.wasi**',
      '**/tutorial/**/*.tsx',
      '**/docs/**',
      '**/node_modules',
      '**/dist',
      '**/package-lock.json',
      '**/yarn.lock',
      '**/pnpm-lock.yaml',
      '**/bun.lockb',
      'output',
      '**/coverage',
      '**/temp',
      '**/fixtures',
      '**/.vitepress/cache',
      '**/.nuxt',
      '**/.vercel',
      '**/.changeset',
      '**/.idea',
      '**/.output',
      '**/.vite-inspect',
      '**/.nitro',
      '**/.context',
      '**/CHANGELOG*.md',
      '**/*.min.*',
      '**/LICENSE*',
      '**/__snapshots__',
      '**/auto-import?(s).d.ts',
      '**/components.d.ts',
      '**/logs',
      '**/*.log',
      '**/npm-debug.log*',
      'ecosystem-ci/workspace',
      '**/pids',
      '**/*.pid',
      '**/*.seed',
      '**/*.pid.lock',
      '**/lib-cov',
      '**/.nyc_output',
      '**/web_modules/',
      '**/bower_components',
      '**/.lock-wscript',
      'build/Release',
      '**/node_modules/',
      '**/jspm_packages/',
      '**/typings/',
      '**/.npm',
      '**/.eslintcache',
      '**/.node_repl_history',
      '**/*.tgz',
      '**/.env',
      '**/.env.development.local',
      '**/.env.test.local',
      '**/.env.production.local',
      '**/.env.local',
      '**/.cache',
      '**/.next',
      '.vuepress/dist',
      '**/.serverless',
      '**/cache',
      '**/debug/',
      '**/target/',
      '**/*.rs.bk',
      '**/*.pdb',
      '**/report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json',
      '**/*.tsbuildinfo',
      '**/.rpt2_cache/',
      '**/.rts2_cache_cjs/',
      '**/.rts2_cache_es/',
      '**/.rts2_cache_umd/',
      '**/.parcel-cache',
      '**/out',
      '**/.cache/',
      '**/.docusaurus',
      '**/.serverless/',
      '**/.fusebox/',
      '**/.dynamodb/',
      '**/.tern-port',
      '**/.vscode-test',
      '.pnpm-store/*',
      '**/*.node',
      '**/*.wasm',
      'packages/compiler/browser.js',
      '**/.webpack/',
      '**/.stylelintcache',
      '**/.svelte-kit',
      '**/.DS_Store',
      '**/.AppleDouble',
      '**/.LSOverride',
      '**/Icon',
      '**/._*',
      '**/.DocumentRevisions-V100',
      '**/.fseventsd',
      '**/.Spotlight-V100',
      '**/.TemporaryItems',
      '**/.Trashes',
      '**/.VolumeIcon.icns',
      '**/.com.apple.timemachine.donotpresent',
      '**/.AppleDB',
      '**/.AppleDesktop',
      '**/Network Trash Folder',
      '**/Temporary Items',
      '**/.apdisk',
      '**/*.icloud',
      '**/flamegraph.svg',
      '**/playground/**',
      'benchmark/**',
      'ecosystem-ci/**',
      'packages/compiler/**',
      'packages/runtime/src/raw.ts',
    ],
    rules: {
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-unassigned-vars': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'error',
      'no-unused-vars': 'error',
      'no-useless-assignment': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-with': 'error',
      'preserve-caught-error': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'array-callback-return': 'error',
      'block-scoped-var': 'error',
      eqeqeq: ['error', 'smart'],
      'no-alert': 'warn',
      'no-console': [
        'warn',
        {
          allow: ['warn', 'error', 'info', 'clear'],
        },
      ],
      'no-duplicate-imports': 'error',
      'no-inner-declarations': 'error',
      'no-lonely-if': 'error',
      'no-multi-str': 'error',
      'no-unused-expressions': [
        'error',
        {
          allowShortCircuit: true,
          allowTaggedTemplates: true,
          allowTernary: true,
        },
      ],
      'no-useless-call': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-constructor': 'error',
      'no-useless-rename': 'error',
      'no-var': 'error',
      'no-void': 'error',
      'object-shorthand': [
        'error',
        'always',
        {
          avoidQuotes: true,
          ignoreConstructors: false,
        },
      ],
      'one-var': [
        'error',
        {
          initialized: 'never',
        },
      ],
      'prefer-arrow-callback': [
        'error',
        {
          allowNamedFunctions: false,
          allowUnboundThis: true,
        },
      ],
      'prefer-const': [
        'warn',
        {
          destructuring: 'all',
          ignoreReadBeforeAssign: true,
        },
      ],
      'prefer-exponentiation-operator': 'error',
      'prefer-regex-literals': [
        'error',
        {
          disallowRedundantWrapping: true,
        },
      ],
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      'require-await': 'error',
      'unicode-bom': ['error', 'never'],
      'vars-on-top': 'error',
      'import/first': 'error',
      'import/no-duplicates': [
        'error',
        {
          preferInline: true,
        },
      ],
      'import/no-mutable-exports': 'error',
      'import/no-named-default': 'error',
      'unicorn/consistent-date-clone': 'error',
      'unicorn/consistent-existence-index-check': 'error',
      'unicorn/error-message': 'error',
      'unicorn/escape-case': 'error',
      'unicorn/import-style': 'error',
      'unicorn/new-for-builtins': 'error',
      'unicorn/no-accessor-recursion': 'error',
      'unicorn/no-array-method-this-argument': 'error',
      'unicorn/no-array-reverse': 'error',
      'unicorn/no-await-in-promise-methods': 'error',
      'unicorn/no-console-spaces': 'error',
      'unicorn/no-document-cookie': 'error',
      'unicorn/no-empty-file': 'error',
      'unicorn/no-hex-escape': 'error',
      'unicorn/no-instanceof-builtins': 'error',
      'unicorn/no-invalid-fetch-options': 'error',
      'unicorn/no-invalid-remove-event-listener': 'error',
      'unicorn/no-lonely-if': 'error',
      'unicorn/no-magic-array-flat-depth': 'error',
      'unicorn/no-negated-condition': 'error',
      'unicorn/no-negation-in-equality-check': 'error',
      'unicorn/no-new-buffer': 'error',
      'unicorn/no-object-as-default-parameter': 'error',
      'unicorn/no-process-exit': 'error',
      'unicorn/no-single-promise-in-promise-methods': 'error',
      'unicorn/no-static-only-class': 'error',
      'unicorn/no-thenable': 'error',
      'unicorn/no-this-assignment': 'error',
      'unicorn/no-typeof-undefined': 'error',
      'unicorn/no-unnecessary-array-flat-depth': 'error',
      'unicorn/no-unnecessary-array-splice-count': 'error',
      'unicorn/no-unnecessary-await': 'error',
      'unicorn/no-unnecessary-slice-end': 'error',
      'unicorn/no-unreadable-array-destructuring': 'error',
      'unicorn/no-unreadable-iife': 'error',
      'unicorn/no-useless-collection-argument': 'error',
      'unicorn/no-useless-error-capture-stack-trace': 'error',
      'unicorn/no-useless-fallback-in-spread': 'error',
      'unicorn/no-useless-iterator-to-array': 'error',
      'unicorn/no-useless-length-check': 'error',
      'unicorn/no-useless-promise-resolve-reject': 'error',
      'unicorn/no-useless-spread': 'error',
      'unicorn/no-useless-switch-case': 'error',
      'unicorn/no-zero-fractions': 'error',
      'unicorn/number-literal-case': 'error',
      'unicorn/numeric-separators-style': 'error',
      'unicorn/prefer-add-event-listener': 'error',
      'unicorn/prefer-array-find': 'error',
      'unicorn/prefer-array-flat': 'error',
      'unicorn/prefer-array-flat-map': 'error',
      'unicorn/prefer-array-index-of': 'error',
      'unicorn/prefer-array-some': 'error',
      'unicorn/prefer-at': 'error',
      'unicorn/prefer-bigint-literals': 'error',
      'unicorn/prefer-blob-reading-methods': 'error',
      'unicorn/prefer-class-fields': 'error',
      'unicorn/prefer-classlist-toggle': 'error',
      'unicorn/prefer-date-now': 'error',
      'unicorn/prefer-default-parameters': 'error',
      'unicorn/prefer-dom-node-append': 'error',
      'unicorn/prefer-dom-node-dataset': 'error',
      'unicorn/prefer-dom-node-text-content': 'error',
      'unicorn/prefer-event-target': 'error',
      'unicorn/prefer-global-this': 'error',
      'unicorn/prefer-includes': 'error',
      'unicorn/prefer-keyboard-event-key': 'error',
      'unicorn/prefer-logical-operator-over-ternary': 'error',
      'unicorn/prefer-math-min-max': 'error',
      'unicorn/prefer-math-trunc': 'error',
      'unicorn/prefer-modern-dom-apis': 'error',
      'unicorn/prefer-modern-math-apis': 'error',
      'unicorn/prefer-module': 'error',
      'unicorn/prefer-native-coercion-functions': 'error',
      'unicorn/prefer-negative-index': 'error',
      'unicorn/prefer-node-protocol': 'error',
      'unicorn/prefer-number-properties': 'error',
      'unicorn/prefer-object-from-entries': 'error',
      'unicorn/prefer-optional-catch-binding': 'error',
      'unicorn/prefer-prototype-methods': 'error',
      'unicorn/prefer-reflect-apply': 'error',
      'unicorn/prefer-regexp-test': 'error',
      'unicorn/prefer-response-static-json': 'error',
      'unicorn/prefer-set-has': 'error',
      'unicorn/prefer-set-size': 'error',
      'unicorn/prefer-single-call': 'error',
      'unicorn/prefer-string-raw': 'error',
      'unicorn/prefer-string-replace-all': 'error',
      'unicorn/prefer-string-slice': 'error',
      'unicorn/prefer-string-starts-ends-with': 'error',
      'unicorn/prefer-string-trim-start-end': 'error',
      'unicorn/prefer-structured-clone': 'error',
      'unicorn/prefer-top-level-await': 'error',
      'unicorn/prefer-type-error': 'error',
      'unicorn/relative-url-style': 'error',
      'unicorn/require-array-join-separator': 'error',
      'unicorn/require-module-attributes': 'error',
      'unicorn/require-module-specifiers': 'error',
      'unicorn/require-number-to-fixed-digits-argument': 'error',
      'unicorn/text-encoding-identifier-case': 'error',
      'unicorn/throw-new-error': 'error',
      'node/handle-callback-err': ['error', '^(err|error)$'],
      'node/no-exports-assign': 'error',
      'node/no-new-require': 'error',
      'node/no-path-concat': 'error',
      'jsdoc/check-access': 'warn',
      'jsdoc/empty-tags': 'warn',
      'jsdoc/require-param-name': 'warn',
      'jsdoc/require-returns-description': 'warn',
      'typescript/dot-notation': 'warn',
      'vite-plus/prefer-vite-plus-imports': 'error',
      'eslint/no-empty': 'off',
      'eslint/no-inner-declarations': 'off',
      'jsdoc/check-tag-names': 'off',
      'typescript/no-base-to-string': 'off',
      'typescript/no-duplicate-type-constituents': 'off',
      'typescript/no-misused-spread': 'off',
      'typescript/no-redundant-type-constituents': 'off',
      'typescript/restrict-template-expressions': 'off',
      'unicorn/no-abusive-eslint-disable': 'off',
      'unicorn/no-array-for-each': 'off',
      'unicorn/no-useless-undefined': 'off',
      'unicorn/prefer-ternary': 'off',
    },
    overrides: [
      {
        files: ['**/*.tsx'],
        rules: {
          'constructor-super': 'off',
          'getter-return': 'off',
          'no-class-assign': 'off',
          'no-const-assign': 'off',
          'no-dupe-class-members': 'off',
          'no-dupe-keys': 'off',
          'no-func-assign': 'off',
          'no-import-assign': 'off',
          'no-new-native-nonconstructor': 'off',
          'no-obj-calls': 'off',
          'no-redeclare': 'off',
          'no-setter-return': 'off',
          'no-this-before-super': 'off',
          'no-undef': 'off',
          'no-unreachable': 'off',
          'no-unsafe-negation': 'off',
          'no-with': 'off',
          'prefer-const': 'error',
        },
      },
      {
        files: ['**/*.?([cm])ts', '**/*.tsx'],
        rules: {
          'no-array-constructor': 'error',
          'no-unused-expressions': [
            'error',
            {
              allowShortCircuit: true,
              allowTaggedTemplates: true,
              allowTernary: true,
            },
          ],
          'typescript/ban-ts-comment': 'off',
          'typescript/no-duplicate-enum-values': 'error',
          'typescript/no-empty-object-type': 'off',
          'typescript/no-explicit-any': 'off',
          'typescript/no-extra-non-null-assertion': 'error',
          'typescript/no-misused-new': 'error',
          'typescript/no-non-null-asserted-optional-chain': 'error',
          'typescript/no-require-imports': 'error',
          'typescript/no-this-alias': 'error',
          'typescript/no-unnecessary-type-constraint': 'error',
          'typescript/no-unsafe-declaration-merging': 'error',
          'typescript/no-unsafe-function-type': 'off',
          'typescript/no-wrapper-object-types': 'error',
          'typescript/prefer-as-const': 'warn',
          'typescript/prefer-namespace-keyword': 'error',
          'typescript/triple-slash-reference': 'error',
          'no-redeclare': 'error',
          'no-unused-vars': 'off',
          'typescript/consistent-type-assertions': [
            'error',
            {
              assertionStyle: 'as',
              objectLiteralTypeAssertions: 'allow-as-parameter',
            },
          ],
          'typescript/consistent-type-imports': [
            'error',
            {
              disallowTypeAnnotations: false,
              fixStyle: 'inline-type-imports',
            },
          ],
          'typescript/method-signature-style': ['error', 'property'],
          'typescript/no-import-type-side-effects': 'error',
          'typescript/no-non-null-assertion': 'off',
          'typescript/prefer-literal-enum-member': [
            'error',
            {
              allowBitwiseExpressions: true,
            },
          ],
        },
      },
      {
        files: ['**/*.d.ts'],
        rules: {
          'import/no-duplicates': 'off',
        },
        jsPlugins: [],
      },
      {
        files: ['**/*.?([cm])js', '**/*.cjs'],
        rules: {
          'typescript/no-require-imports': 'off',
        },
      },
      {
        files: ['*.yaml', '**/*.yaml', '*.yml', '**/*.yml'],
        rules: {
          'no-irregular-whitespace': 'off',
          'no-unused-vars': 'off',
        },
      },
      {
        files: ['**/*.y?(a)ml'],
        rules: {},
        jsPlugins: [],
      },
      {
        files: ['*.json', '**/*.json', '*.json5', '**/*.json5', '*.jsonc', '**/*.jsonc'],
        rules: {
          'no-unused-expressions': 'off',
          'no-unused-vars': 'off',
        },
      },
      {
        files: ['**/package.json'],
        rules: {},
        jsPlugins: [],
      },
      {
        files: ['**/[jt]sconfig.json', '**/[jt]sconfig.*.json'],
        rules: {},
        jsPlugins: [],
      },
      {
        files: ['**/pnpm-workspace.yaml'],
        rules: {},
        jsPlugins: [],
      },
      {
        files: ['**/*.md/**'],
        rules: {
          'no-undef': 'off',
          'no-unused-expressions': 'off',
          'no-unused-vars': 'off',
          'unicode-bom': 'off',
        },
      },
      {
        files: ['**/*.md/**/*.?([cm])[jt]s?(x)', '**/*.md/**/*.vue'],
        rules: {
          'no-alert': 'off',
          'no-console': 'off',
          'no-restricted-imports': 'off',
          'no-undef': 'off',
          'no-unused-expressions': 'off',
          'no-unused-vars': 'off',
          'unicorn/no-useless-undefined': 'off',
          'no-redeclare': 'off',
          'no-use-before-define': 'off',
          'typescript/consistent-type-imports': 'off',
          'typescript/no-extraneous-class': 'off',
          'typescript/no-require-imports': 'off',
        },
        jsPlugins: [],
      },
      {
        files: ['**/scripts/*', '**/cli.*'],
        rules: {
          'no-console': 'off',
        },
        jsPlugins: [],
      },
      {
        files: ['**/*.{test,spec}.?([cm])[jt]s?(x)'],
        rules: {
          'no-unused-expressions': 'off',
        },
        jsPlugins: [],
      },
      {
        files: ['**/*.md/*.tsx'],
        rules: {
          'no-var': 'off',
          'no-duplicate-imports': 'off',
          'import/first': 'off',
        },
      },
    ],
  },
})
