/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface CompilerError extends SyntaxError {
  code: number
  loc?: [number, number]
}

export declare const enum ErrorCodes {
  VIfNoExpression = 28,
  VElseNoAdjacentIf = 30,
  VForNoExpression = 31,
  VForMalformedExpression = 32,
  VOnNoExpression = 35,
  VSlotUnexpectedDirectiveOnSlotOutlet = 36,
  VSlotMixedSlotUsage = 37,
  VSlotDuplicateSlotNames = 38,
  VSlotExtraneousDefaultSlotChildren = 39,
  VSlotMisplaced = 40,
  VModelNoExpression = 41,
  VModelMalformedExpression = 42,
  KeepAliveInvalidChildren = 46,
  VHtmlNoExpression = 53,
  VHtmlWithChildren = 54,
  VTextNoExpression = 55,
  VTextWithChildren = 56,
  VModelOnInvalidElement = 57,
  VModelArgOnElement = 58,
  VModelOnFileInputElement = 59,
  VModelUnnecessaryValue = 60,
  VShowNoExpression = 61,
  VSlotsNoExpression = 62
}

export interface Hmr {
  /** * The name of the function to be used for defining components.
   * This is useful when you have a custom defineComponent function.
   * @default ['defineComponent', 'defineVaporComponent']
   */
  defineComponentName: Array<string>
}
export interface CompilerOptions {
  onError?: (arg: object) => void
  onWarn?: (arg: object) => void
  /**
   * Generate source map?
   * @default false
   */
  sourceMap?: boolean
  /**
   * Filename for source map generation.
   * Also used for self-recursive reference in templates
   * @default 'index.jsx'
   */
  filename?: string
  /**
   * Transform JSX for Vapor Mode.
   * @default false
   */
  vapor?: boolean
  /**
   * Enabled HMR support.
   * - `true`/`false`: a boolean to simply enable/disable HMR. When `true`, HMR
   *   is enabled with default configuration.
   * - `Hmr`: an object to enable HMR with custom configuration.
   * @default false
   */
  hmr?: boolean | Hmr
  /**
   * Enabled SSR support.
   * @default false
   */
  ssr?: boolean
  /**
   * Whether to enable compiler optimizations, including:
   * - **Slots**: Detect if slots are stable for more efficient updates.
   * - **Cache**: Cache event handler to avoid recreating closures on each render.
   * - **Block**: Enable block tree optimizations.
   *
   * Note: this option is only used in Virtual DOM mode.
   * @default true
   */
  optimize?: boolean
  /**
   * Customize where to import runtime helpers from vue-jsx-vapor.
   * If not specified, defaults to the virtual module path (e.g., `/vue-jsx-vapor/vapor`).
   */
  runtimeModuleName?: string
  /**
   * Whether to merge props when using JSXSpreadAttribute.
   * - `true`: Use Vue's `mergeProps` behavior
   *   - Event listeners (`onXxx`) are merged into an array
   *   - `class` and `style` are normalized and merged
   *   - Other props are overridden by later values
   * - `false`: later props override earlier ones (like object spread)
   * @default true
   */
  mergeProps?: boolean
}

export declare function transform(source: string, options?: CompilerOptions | undefined | null): TransformReturn

export interface TransformReturn {
  code: string
  map?: string
}
