/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface CompilerError extends SyntaxError {
  code: number
  loc?: [number, number]
}

export declare const enum ErrorCodes {
  VIfNoExpression = 28,
  VElseNoAdjacentIf = 30,
  VForNoExpression = 31,
  VForMalformedExpression = 32,
  VForTemplateKeyPlacement = 33,
  VOnNoExpression = 35,
  VSlotMixedSlotUsage = 37,
  VSlotDuplicateSlotNames = 38,
  VSlotExtraneousDefaultSlotChildren = 39,
  VSlotMisplaced = 40,
  VModelNoExpression = 41,
  VModelMalformedExpression = 42,
  KeepAliveInvalidChildren = 46,
  VHtmlNoExpression = 53,
  VHtmlWithChildren = 54,
  VTextNoExpression = 55,
  VTextWithChildren = 56,
  VModelOnInvalidElement = 57,
  VModelArgOnElement = 58,
  VModelOnFileInputElement = 59,
  VModelUnnecessaryValue = 60,
  VShowNoExpression = 61,
  VSlotsNoExpression = 62
}
export declare function transform(source: string, options?: TransformOptions | undefined | null): TransformReturn

export interface TransformOptions {
  /** * Whether to compile components to createComponentWithFallback.
   * @default false
   */
  withFallback?: boolean
  /** * Separate option for end users to extend the native elements list
   */
  isCustomElement?: (arg: string) => boolean
  onError?: (arg: object) => void
  /** * Generate source map?
   * @default false
   */
  sourceMap?: boolean
  /** * Filename for source map generation.
   * Also used for self-recursive reference in templates
   * @default 'index.jsx'
   */
  filename?: string
  /** * When enabled, JSX within `defineVaporComponent` is transformed to Vapor DOM,
   * while all other JSX is transformed to Virtual DOM.
   */
  interop?: boolean
  /** * Enabled HMR support.
   * @default false
   */
  hmr?: boolean
  /** * Enabled SSR support.
   * @default false
   */
  ssr?: boolean
}

export interface TransformReturn {
  code: string
  map?: string
}
